import { useApp } from '../context/AppContext.jsx';
import { unitPriceCents, formatMoney } from '../lib/pricing.js';

/**
 * For returning visitors who've taken the quiz, surface their match
 * prominently on the homepage. If there's no saved result (guest, or
 * logged-in user who hasn't taken the quiz), renders nothing.
 *
 * The match data lives on user.quizResult and contains { name, brand,
 * description, tags, why }, all generated by the AI quiz endpoint.
 * When the match resolves to a catalog entry, the primary CTA is a
 * one-click 2ml add-to-cart with a live price — the quiz should end
 * in a purchase, not another modal.
 */
export function QuizMatchCard() {
  const { user, fragrances, addToCart, openCart, showToast, openSampleModal, openSourceModal } = useApp();
  const result = user?.quizResult;
  if (!result?.name) return null;

  const label = `${result.name}, ${result.brand}`;
  const matched = fragrances.find(f =>
    f.name.toLowerCase() === String(result.name).toLowerCase());

  function addMatch() {
    addToCart({ fragranceId: matched.id, name: matched.name, brand: matched.brand, size: '2ml', qty: 1 });
    showToast(`<span>Added</span> 2ml of ${matched.name} to cart`);
    openCart();
  }

  return (
    <section className="quiz-match-card">
      <div className="quiz-match-inner">
        <p className="quiz-match-eyebrow">Your match · from the quiz</p>
        <h2 className="quiz-match-title">
          We picked <em className="gradient-em">{result.name}</em>
        </h2>
        <p className="quiz-match-brand">{result.brand}</p>
        <p className="quiz-match-desc">{result.description}</p>
        {Array.isArray(result.tags) && result.tags.length > 0 && (
          <div className="quiz-match-tags">
            {result.tags.map(t => <span key={t} className="quiz-match-tag">{t}</span>)}
          </div>
        )}
        <div className="quiz-match-actions">
          {matched ? (
            <button type="button" className="btn-gold" onClick={addMatch}>
              Add 2ml to Cart · {formatMoney(unitPriceCents('2ml', matched.id))}
            </button>
          ) : (
            <button type="button" className="btn-gold" onClick={() => openSampleModal(label)}>
              Order a Sample
            </button>
          )}
          <button type="button" className="btn-ghost quiz-match-ghost" onClick={() => openSourceModal(label)}>
            Source Full Bottle
          </button>
        </div>
      </div>
    </section>
  );
}
